import { SportsEvent } from '../types';

export const INITIAL_EVENTS: SportsEvent[] = [
  {
    id: '1',
    title: 'Galatasaray - Fenerbahçe Derbisi',
    slug: 'gs-fb-derbi-2026',
    category: 'Spor Etkinlikleri',
    city: 'İstanbul',
    venue: 'RAMS Park',
    date: '20 Ekim 2026',
    time: '20:00',
    organizer: 'Sporpuan Onaylı Organizasyon',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?q=80&w=1200&auto=format&fit=crop',
    description: 'Süper Lig heyecanı dev derbi ile devam ediyor. İki ezeli rakip RAMS Park\'ta karşı karşıya geliyor.',
    ticketPriceRange: '₺1000 - ₺5000',
    ticketUrl: 'https://passo.com.tr',
    overallScore: 8.8,
    ratingBreakdown: {
      organizasyonAkis: 8.5,
      parkurGuvenlik: 8.8,
      kitIkram: 8.0,
      atmosferSeyir: 9.8,
      biletFiyat: 7.2
    },
    reviewCount: 450,
    featured: false,
    tags: ['Futbol', 'Süper Lig', 'Derbi'],
    aiSummary: {
      tr: 'RAMS Park derbi atmosferi ve tribün akustiği seyircilerden tam not almaktadır. Giriş turnikelerindeki yoğunluk ve maç sonu otopark çıkış süreleri haricinde organizasyon akışı son derece başarılıdır.',
      en: 'The derbi atmosphere and stadium acoustics at RAMS Park receive top ratings from fans. Despite crowd bottlenecks at entry turnstiles and post-match parking delays, the overall event execution is highly impressive.',
      highlightsTr: ['Devamlı Tribün Coşkusu', 'Yüksek Güvenlik Önlemleri', 'Otopark Yoğunluğu'],
      highlightsEn: ['Electric Stadium Atmosphere', 'Strict Safety Measures', 'Heavy Post-Match Traffic']
    },
    reviews: [
      {
        id: 'r1',
        userName: 'Ahmet Yılmaz',
        verifiedAttendee: true,
        date: '21 Ekim 2026',
        overallScore: 8.8,
        scores: {
          organizasyonAkis: 8.5,
          parkurGuvenlik: 8.8,
          kitIkram: 8.0,
          atmosferSeyir: 9.8,
          biletFiyat: 7.2
        },
        comment: 'Atmosfer mükemmeldi, tribün akustiği inanılmaz coşkulu. Ancak stadyuma giriş çıkışlarda turnikelerde çok sıra bekledik.',
        englishComment: 'The atmosphere was unmatched and the stadium acoustics were electric. However, we experienced long queues at the entry turnstiles.',
        pros: ['Harika Atmosfer', 'Stadyum Akustiği', 'Net Görüş Açısı'],
        cons: ['Otopark Yoğunluğu', 'Yüksek Bilet Fiyatı'],
        likes: 120,
        tags: ['Atmosfer', 'Trafik']
      },
      {
        id: 'r1-2',
        userName: 'Selin Erdem',
        verifiedAttendee: true,
        date: '21 Ekim 2026',
        overallScore: 9.2,
        scores: {
          organizasyonAkis: 9.0,
          parkurGuvenlik: 9.5,
          kitIkram: 8.5,
          atmosferSeyir: 10.0,
          biletFiyat: 8.0
        },
        comment: 'Stadyum içi yönlendirmeler ve özel güvenlik personeli çok yardımcı oldu. Taraftar şovları unutulmaz bir deneyim sundu.',
        englishComment: 'Stadium signage and security personnel were very helpful. The fan displays and choreographies offered an unforgettable experience.',
        pros: ['Başarılı Güvenlik', 'Unutulmaz Şovlar'],
        cons: ['Büfe Kuyrukları'],
        likes: 84,
        tags: ['Organizasyon', 'Coşku']
      },
      {
        id: 'r1-3',
        userName: 'Burak Demir',
        verifiedAttendee: true,
        date: '22 Ekim 2026',
        overallScore: 8.4,
        scores: {
          organizasyonAkis: 8.0,
          parkurGuvenlik: 8.5,
          kitIkram: 7.5,
          atmosferSeyir: 9.5,
          biletFiyat: 6.5
        },
        comment: 'Metroya ulaşım maç sonu biraz zaman alıyor fakat stadyum içi konfor ve ikram alanı kalitesi çok yüksek.',
        englishComment: 'Reaching the metro after the match takes some time, but the stadium interior comfort and catering zone quality are very high.',
        pros: ['Konforlu Koltuklar', 'Kaliteli Büfe'],
        cons: ['Metro Kalabalığı'],
        likes: 42,
        tags: ['Metro', 'Konfor']
      }
    ],
    latitude: 41.1034,
    longitude: 28.9912,
  },
  {
    id: '2',
    title: 'MacFit Kanyon',
    slug: 'macfit-kanyon',
    category: 'Spor Salonları',
    city: 'İstanbul',
    venue: 'Kanyon AVM, Levent',
    date: 'Her Gün',
    time: '07:00 - 23:00',
    organizer: 'MacFit',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1200&auto=format&fit=crop',
    description: 'Levent\'in merkezinde, son teknoloji ekipmanlarla donatılmış ferah bir spor salonu deneyimi.',
    ticketPriceRange: '₺800 - ₺1200 (Aylık)',
    ticketUrl: 'https://macfit.com',
    overallScore: 7.8,
    ratingBreakdown: {
      ekipmanCesit: 8.8,
      hijyenFerahlik: 8.2,
      antrenorDestegi: 7.0,
      yogunlukAtmosfer: 6.5,
      fiyatUyelik: 7.5
    },
    reviewCount: 125,
    featured: false,
    tags: ['Fitness', 'Gym', 'Levent'],
    aiSummary: {
      tr: 'Levent merkezindeki lokasyonu ve modern ekipman çeşitliliği tesisin en güçlü yanlarıdır. İş çıkış saatlerinde (18:00 - 20:30) oluşan kalabalık dışında temizlik ve cardio olanakları üst seviyededir.',
      en: 'Its prime central Levent location and modern equipment variety are key strengths. Apart from peak post-work rush hours (6:00 PM - 8:30 PM), hygiene standards and cardio facilities are top notch.',
      highlightsTr: ['Son Teknoloji Ekipman', 'Merkezi Lokasyon', 'Akşam Saatleri Kalabalık'],
      highlightsEn: ['State-of-the-art Equipment', 'Central Location', 'Peak Hour Crowds']
    },
    reviews: [
      {
        id: 'r2',
        userName: 'Zeynep Kaya',
        verifiedAttendee: true,
        date: '10 Ekim 2026',
        overallScore: 7.8,
        scores: {
          ekipmanCesit: 8.8,
          hijyenFerahlik: 8.2,
          antrenorDestegi: 7.0,
          yogunlukAtmosfer: 6.5,
          fiyatUyelik: 7.5
        },
        comment: 'Akşam saatlerinde çok kalabalık oluyor ama genel olarak temiz ve serbest ağırlık ekipmanları gayet yeterli.',
        englishComment: 'Gets very crowded in the evenings, but overall clean and free weight equipment is more than sufficient.',
        pros: ['Merkezi Konum', 'Yüksek Temizlik Standardı'],
        cons: ['Akşam Yoğunluğu', 'Eğitmen İlgisizliği'],
        likes: 45,
        tags: ['Kalabalık', 'Temiz']
      },
      {
        id: 'r2-2',
        userName: 'Mert Aksoy',
        verifiedAttendee: true,
        date: '18 Ekim 2026',
        overallScore: 8.4,
        scores: {
          ekipmanCesit: 9.0,
          hijyenFerahlik: 8.5,
          antrenorDestegi: 7.5,
          yogunlukAtmosfer: 8.0,
          fiyatUyelik: 8.0
        },
        comment: 'Sabah 07:00 seansında sakin ve son derece keyifli. Soyunma odalarındaki duşların bakımı çok iyi.',
        englishComment: 'Very calm and enjoyable during the 7:00 AM session. Locker room showers are very well-maintained.',
        pros: ['Sabah Sakinliği', 'Steril Soyunma Odaları'],
        cons: ['Otopark Ücretli'],
        likes: 29,
        tags: ['Sabah Antrenmanı', 'Hijyen']
      }
    ],
    latitude: 41.0772,
    longitude: 29.0116,
  },
  {
    id: '3',
    title: 'Fenerbahçe Futbol Okulu',
    slug: 'fb-futbol-okulu',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Dereağzı Lefter Küçükandonyadis Tesisleri',
    date: 'Hafta Sonu',
    time: '09:00 - 15:00',
    organizer: 'Fenerbahçe SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?q=80&w=1200&auto=format&fit=crop',
    description: "Geleceğin yıldızları için profesyonel altyapı eğitimi.",
    ticketPriceRange: '₺2000 (Aylık)',
    ticketUrl: 'https://fenerbahce.org',
    overallScore: 9.1,
    ratingBreakdown: {
      egitmenKalitesi: 9.6,
      mufredatGelisim: 9.2,
      guvenlikDisiplin: 9.0,
      tesisEkipman: 8.8,
      fiyatIletisim: 8.5
    },
    reviewCount: 85,
    featured: false,
    tags: ['Futbol Okulu', 'Çocuk', 'Eğitim'],
    aiSummary: {
      tr: 'Dereağzı Tesisleri altyapı antrenörlerinin uzmanlığı ve çocuklarla iletişimi velilerden büyük takdir almaktadır. Saha kalitesi ve disiplin ilkeleri üst düzeydedir.',
      en: 'The expertise and child pedagogy of the Dereağzı academy coaches earn high praise from parents. Pitch condition and discipline principles are exceptional.',
      highlightsTr: ['Lisanslı Uzman Kadro', 'Disiplinli Müfredat', 'Güvenli Tesis'],
      highlightsEn: ['Certified Expert Staff', 'Disciplined Curriculum', 'Secure Facility']
    },
    reviews: [
      {
        id: 'r3',
        userName: 'Can Yılmaz',
        verifiedAttendee: true,
        date: '02 Eylül 2026',
        overallScore: 9.1,
        scores: {
          egitmenKalitesi: 9.6,
          mufredatGelisim: 9.2,
          guvenlikDisiplin: 9.0,
          tesisEkipman: 8.8,
          fiyatIletisim: 8.5
        },
        comment: 'Çocuğum büyük bir keyifle gidiyor, hocalar gerçekten çok ilgili ve alanında uzman sporcu ahlakını çok iyi aşılıyorlar.',
        englishComment: 'My child goes with absolute joy! Coaches are very attentive, highly expert, and instill strong athletic morals.',
        pros: ['Profesyonel Eğitmenler', 'Harika Tesisler', 'Disiplin'],
        cons: ['Ulaşım Bazen Yoğun'],
        likes: 22,
        tags: ['Eğitim Kalitesi', 'İlgili Personel']
      },
      {
        id: 'r3-2',
        userName: 'Hande Öztürk',
        verifiedAttendee: true,
        date: '15 Eylül 2026',
        overallScore: 9.0,
        scores: {
          egitmenKalitesi: 9.5,
          mufredatGelisim: 9.0,
          guvenlikDisiplin: 9.2,
          tesisEkipman: 8.5,
          fiyatIletisim: 8.8
        },
        comment: 'Veliler için tribün izleme alanı rahat, turnuvalar ve gelişim raporları düzenli olarak iletiliyor.',
        englishComment: 'Parent viewing area is comfortable; student development reports and tournaments are shared regularly.',
        pros: ['Düzenli Raporlama', 'Geniş İzleme Tribünü'],
        cons: ['Kafeterya Fiyatları'],
        likes: 18,
        tags: ['Veli Memnuniyeti', 'Altyapı']
      }
    ],
    latitude: 40.9763,
    longitude: 28.7997,
  },
  {
    id: '4',
    title: 'Sinan Erdem Kapalı Spor Salonu',
    slug: 'sinan-erdem-salon',
    category: 'Spor Tesisleri',
    city: 'İstanbul',
    venue: 'Ataköy',
    date: 'Her Gün',
    time: '08:00 - 22:00',
    organizer: 'Sinan Erdem Spor Tesisleri A.Ş.',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=1200&auto=format&fit=crop',
    description: 'Türkiye\'nin en büyük kapalı spor salonlarından biri. Çok amaçlı saha kiralama imkanı.',
    ticketPriceRange: '₺500 - ₺1000 (Saatlik)',
    ticketUrl: 'https://sporpuan.com',
    overallScore: 8.2,
    ratingBreakdown: {
      zeminSaha: 9.2,
      soyunmaHijyen: 8.5,
      ekipmanAydinlatma: 8.8,
      ulasimOtopark: 6.2,
      fiyatHizmet: 7.8
    },
    reviewCount: 310,
    featured: false,
    tags: ['Basketbol', 'Tesis Kiralama', 'Kapalı Salon'],
    aiSummary: {
      tr: 'Basketbol zemin kalitesi ve uluslararası standartlardaki potaları tesisin en güçlü yanıdır. Büyük maç günlerinde otopark kısıtı yaşanabilse de saha kiralama ve ışıklandırma mükemmeldir.',
      en: 'Court flooring and FIBA-standard basketball hoops represent the facility\'s highlights. While parking fills up on major match days, court rentals and lighting setup remain top-tier.',
      highlightsTr: ['Uluslararası Zemin Standardı', 'Güçlü Aydınlatma', 'Maç Günü Otopark Sıkıntısı'],
      highlightsEn: ['FIBA Standard Flooring', 'Bright Arena Lighting', 'Match-Day Parking Congestion']
    },
    reviews: [
      {
        id: 'r4',
        userName: 'Mehmet Y.',
        verifiedAttendee: true,
        date: '15 Kasım 2026',
        overallScore: 8.2,
        scores: {
          zeminSaha: 9.2,
          soyunmaHijyen: 8.5,
          ekipmanAydinlatma: 8.8,
          ulasimOtopark: 6.2,
          fiyatHizmet: 7.8
        },
        comment: 'Tesis çok büyük ve zemin imkanları mükemmel, ancak dev etkinlik günlerinde otopark girişi zaman alabiliyor.',
        englishComment: 'Facility is massive and court flooring is excellent, though parking access takes time on major event days.',
        pros: ['Tesis Büyüklüğü', 'Ahşap Zemin Kalitesi'],
        cons: ['Otopark Yetersizliği'],
        likes: 67,
        tags: ['Park Yeri Yok', 'Ferah Ortam']
      },
      {
        id: 'r4-2',
        userName: 'Ege Kuru',
        verifiedAttendee: true,
        date: '20 Kasım 2026',
        overallScore: 8.6,
        scores: {
          zeminSaha: 9.5,
          soyunmaHijyen: 8.8,
          ekipmanAydinlatma: 9.0,
          ulasimOtopark: 7.0,
          fiyatHizmet: 8.0
        },
        comment: 'Hafta içi amatör lig maçları için kiraladık. Soyunma odalarındaki sıcak su ve hijyen harikaydı.',
        englishComment: 'Rented for amateur league matches on a weekday. Hot water and locker room cleanliness were brilliant.',
        pros: ['Sıcak Duşlar', 'Harika Işıklandırma'],
        cons: ['Kantin Seçenekleri Az'],
        likes: 35,
        tags: ['Saha Kiralama', 'Temiz Soyunma']
      }
    ],
    latitude: 40.9902,
    longitude: 28.8507,
  },
  {
    id: '5',
    title: 'Olimpik Yüzme Havuzu Kompleksi',
    slug: 'ankara-olimpik-havuz',
    category: 'Spor Tesisleri',
    city: 'Ankara',
    venue: 'Eryaman',
    date: 'Her Gün',
    time: '06:00 - 22:00',
    organizer: 'Ankara Spor Kompleksi Yönetimi',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?q=80&w=1200&auto=format&fit=crop',
    description: "Olimpik standartlarda, her yaşa ve seviyeye uygun temiz ve modern yüzme tesisi.",
    ticketPriceRange: '₺150 - ₺300 (Günlük Giriş)',
    ticketUrl: 'https://sporpuan.com',
    overallScore: 8.9,
    ratingBreakdown: {
      zeminSaha: 9.5,
      soyunmaHijyen: 9.0,
      ekipmanAydinlatma: 9.2,
      ulasimOtopark: 8.0,
      fiyatHizmet: 8.8
    },
    reviewCount: 205,
    featured: true,
    tags: ['Yüzme', 'Olimpik Havuz', 'Su Sporları'],
    aiSummary: {
      tr: 'Ankara Eryaman\'daki olimpik havuz, su sıcaklığı dengesi, klor filtreleme kalitesi ve geniş kulvar imkanıyla yüzücülerden tam not almaktadır.',
      en: 'The Eryaman Olympic Pool in Ankara receives outstanding reviews for its water temperature balance, advanced filtration system, and ample swim lanes.',
      highlightsTr: ['Steril Havuz Suyu', 'Geniş Kulvar Alanı', 'Hafta Sonu Yoğunluğu'],
      highlightsEn: ['Sterile Pool Water', 'Spacious Swim Lanes', 'Weekend Family Crowds']
    },
    reviews: [
      {
        id: 'r5',
        userName: 'Aylin Çelik',
        verifiedAttendee: true,
        date: '12 Ağustos 2026',
        overallScore: 8.9,
        scores: {
          zeminSaha: 9.5,
          soyunmaHijyen: 9.0,
          ekipmanAydinlatma: 9.2,
          ulasimOtopark: 8.0,
          fiyatHizmet: 8.8
        },
        comment: 'Çok temiz bir havuz, su sıcaklığı ve klor oranı ideal. Cankurtaran ekibi sürekli kulvar takibi yapıyor.',
        englishComment: 'Extremely clean pool; water temperature and chlorination level are ideal. Lifeguards actively monitor swim lanes.',
        pros: ['Temizlik ve Hijyen', 'Uygun Fiyat', 'Cankurtaran İlgisi'],
        cons: ['Haftasonu Kalabalığı'],
        likes: 88,
        tags: ['Temiz Su', 'Aile Ortamı']
      },
      {
        id: 'r5-2',
        userName: 'Tarkan Özen',
        verifiedAttendee: true,
        date: '25 Ağustos 2026',
        overallScore: 9.1,
        scores: {
          zeminSaha: 9.6,
          soyunmaHijyen: 9.2,
          ekipmanAydinlatma: 9.0,
          ulasimOtopark: 8.5,
          fiyatHizmet: 9.0
        },
        comment: 'Sabah 06:30 antrenmanlarında performans kulvarları boş ve su berraklığı harika. Soyunma dolapları dijital sistemli.',
        englishComment: 'Early morning 6:30 AM sessions feature empty performance lanes and crystal-clear water. Lockers use modern digital keypads.',
        pros: ['Berrak Havuz Suyu', 'Dijital Dolaplar'],
        cons: ['B bone Zorunluluğu'],
        likes: 54,
        tags: ['Yüzme', 'Performans']
      }
    ],
    latitude: 39.9575,
    longitude: 32.6105,
  },
  {
    id: '6',
    title: 'Iron Peak Gym',
    slug: 'iron-peak-gym-izmir',
    category: 'Spor Salonları',
    city: 'İzmir',
    venue: 'Karşıyaka',
    date: 'Her Gün',
    time: '06:30 - 00:00',
    organizer: 'Iron Peak',
    organizerVerified: false,
    image: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=1200&auto=format&fit=crop',
    description: "Özellikle serbest ağırlık ve CrossFit meraklıları için tasarlanmış geniş donanımlı butik salon.",
    ticketPriceRange: '₺1000 (Aylık)',
    ticketUrl: '',
    overallScore: 9.3,
    ratingBreakdown: {
      ekipmanCesit: 9.8,
      hijyenFerahlik: 8.8,
      antrenorDestegi: 9.4,
      yogunlukAtmosfer: 9.0,
      fiyatUyelik: 9.2
    },
    reviewCount: 92,
    featured: false,
    tags: ['CrossFit', 'Vücut Geliştirme', 'Karşıyaka'],
    aiSummary: {
      tr: 'Karşıyaka\'da serbest ağırlık çeşitliliği (60 kg dambıl skalamız) ve yüksek enerjili müzik atmosferiyle ağırlık sporcularının gözdesidir.',
      en: 'A top favorite for heavy lifters in Karşıyaka thanks to free weight options (dumbbells up to 60 kg) and an energetic workout environment.',
      highlightsTr: ['Zengin Serbest Ağırlık', 'Motive Edici Atmosfer', 'Ağırlık Platformları'],
      highlightsEn: ['Vast Free-Weight Selection', 'Motivating Vibe', 'Deadlift Platforms']
    },
    reviews: [
      {
        id: 'r6',
        userName: 'Mert Tekin',
        verifiedAttendee: true,
        date: '04 Eylül 2026',
        overallScore: 9.3,
        scores: {
          ekipmanCesit: 9.8,
          hijyenFerahlik: 8.8,
          antrenorDestegi: 9.4,
          yogunlukAtmosfer: 9.0,
          fiyatUyelik: 9.2
        },
        comment: 'Ekipmanlar mükemmel, gerçek bir hardcore spor salonu atmosferi var. Müzikler de antrenman temposunu yükseltiyor!',
        englishComment: 'Equipment is top-notch with an authentic hardcore gym atmosphere. Playlists elevate workout intensity!',
        pros: ['Serbest Ağırlık Çeşitliliği', 'Harika Atmosfer'],
        cons: ['Havalandırma Bazen Yetersiz'],
        likes: 31,
        tags: ['Hardcore Gym', 'Ağırlıklar']
      },
      {
        id: 'r6-2',
        userName: 'Bora Güven',
        verifiedAttendee: true,
        date: '14 Eylül 2026',
        overallScore: 9.4,
        scores: {
          ekipmanCesit: 9.7,
          hijyenFerahlik: 9.0,
          antrenorDestegi: 9.5,
          yogunlukAtmosfer: 9.2,
          fiyatUyelik: 9.3
        },
        comment: 'CrossFit parkuru ve barbell platformları çok kaliteli. Koçlar form kontrolüne dikkat ediyor.',
        englishComment: 'CrossFit rig and barbell platforms are high quality. Coaches pay close attention to lifting form.',
        pros: ['Profesyonel Koçlar', 'Geniş CrossFit Rig'],
        cons: ['Park Yeri Kısıtlı'],
        likes: 19,
        tags: ['CrossFit', 'Koçluk']
      }
    ],
    latitude: 38.4550,
    longitude: 27.1141,
  },
  {
    id: '7',
    title: 'Göztepe Yelken Kulübü',
    slug: 'goztepe-yelken',
    category: 'Spor Tesisleri',
    city: 'İzmir',
    venue: 'Güzelyalı, Sahil Şeridi',
    date: 'Her Gün',
    time: '09:00 - 18:00',
    organizer: 'Göztepe SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1534125867375-7bc6bb8544d6?q=80&w=1200&auto=format&fit=crop',
    description: 'Ege\'nin sularında profesyonel yelken eğitimi ve tekne kiralama hizmeti sunan köklü tesis.',
    ticketPriceRange: '₺4000 (Aylık Kurs)',
    ticketUrl: 'https://goztepe.org.tr',
    overallScore: 8.5,
    ratingBreakdown: {
      zeminSaha: 8.8,
      soyunmaHijyen: 8.2,
      ekipmanAydinlatma: 8.5,
      ulasimOtopark: 8.0,
      fiyatHizmet: 8.6
    },
    reviewCount: 65,
    featured: true,
    tags: ['Yelken', 'Deniz Sporları', 'Kurs'],
    aiSummary: {
      tr: 'İzmir Güzelyalı sahilinde deneyimli kaptanlar ve eğitmenlerle Ege denizinde yelken sporunu öğrenmek için ideal bir lokasyondur.',
      en: 'Located on the Izmir Güzelyalı coast, this venue offers an ideal setting to learn sailing in the Aegean with seasoned captains.',
      highlightsTr: ['Deneyimli Kaptanlar', 'Güzelyalı Sahil Konumu', 'Ekipman Bakım İhtiyacı'],
      highlightsEn: ['Seasoned Captains', 'Güzelyalı Coastline', 'Fleet Maintenance Needs']
    },
    reviews: [
      {
        id: 'r7',
        userName: 'Burcu Yılmaz',
        verifiedAttendee: true,
        date: '18 Mayıs 2026',
        overallScore: 8.5,
        scores: {
          zeminSaha: 8.8,
          soyunmaHijyen: 8.2,
          ekipmanAydinlatma: 8.5,
          ulasimOtopark: 8.0,
          fiyatHizmet: 8.6
        },
        comment: 'Hocalarımız son derece yetkin ve rüzgar okumayı harika öğretiyorlar. Tesis lokasyonu Ege manzarasında büyüleyici.',
        englishComment: 'Instructors are extremely skilled and teach wind reading thoroughly. Location boasts stunning Aegean views.',
        pros: ['Uzman Eğitmen Kadrosu', 'Mükemmel Lokasyon'],
        cons: ['Teknelerin Yenilenme İhtiyacı'],
        likes: 12,
        tags: ['Eğitim', 'Manzara']
      },
      {
        id: 'r7-2',
        userName: 'Kaan Sezer',
        verifiedAttendee: true,
        date: '28 Mayıs 2026',
        overallScore: 8.7,
        scores: {
          zeminSaha: 9.0,
          soyunmaHijyen: 8.5,
          ekipmanAydinlatma: 8.5,
          ulasimOtopark: 8.2,
          fiyatHizmet: 8.5
        },
        comment: 'Deniz güvenliği ekipmanları ve can yelekleri sıfır ayarında. Teorik ders anlatımı çok bilgilendirici.',
        englishComment: 'Sea safety gear and life jackets are in mint condition. Theory lectures are deeply informative.',
        pros: ['Sıkı Güvenlik Standardı', 'Anlaşılır Teorik Eğitim'],
        cons: ['Hafta Sonu Yoğunluğu'],
        likes: 8,
        tags: ['Güvenlik', 'Deniz']
      }
    ],
    latitude: 38.3965,
    longitude: 27.0864,
  },
  {
    id: 'school-1',
    title: 'Galatasaray Futbol Okulu (Florya)',
    slug: 'gs-futbol-okulu-florya',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Florya Metin Oktay Tesisleri',
    date: 'Tüm Yıl',
    organizer: 'Galatasaray SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1574629810360-7efbb928ac05?q=80&w=1200&auto=format&fit=crop',
    description: "Galatasaray Futbol Okulu, geleceğin yıldızlarını yetiştiriyor. Uzman antrenörler eşliğinde profesyonel futbol eğitimi.",
    overallScore: 9.1,
    ratingBreakdown: { antrenor: 9.5, tesis: 9.0, hijyen: 8.5 },
    reviewCount: 120,
    featured: true,
    isActive: true,
    tags: ['Futbol', 'Altyapı', 'Çocuk Sporu'],
    aiSummary: {
      tr: 'Florya Metin Oktay Tesisleri çim kalitesi, disiplinli antrenör kadrosu ve köklü futbol kültürüyle genç sporcular için örnek bir akademidir.',
      en: 'Florya Metin Oktay Facilities offer pristine pitches, disciplined coaches, and an iconic academy culture for youth development.',
      highlightsTr: ['Florya Çim Sahaları', 'Milli Lisanslı Hocalar', 'Kafeterya Kalabalığı'],
      highlightsEn: ['Natural Grass Pitches', 'National Level Coaches', 'Cafeteria Crowds']
    },
    reviews: [
      {
        id: 'r-sch1-1',
        userName: 'Deniz Güneş',
        verifiedAttendee: true,
        date: '10 Haziran 2026',
        overallScore: 9.2,
        scores: { antrenor: 9.6, tesis: 9.2, hijyen: 8.8 },
        comment: 'Oğlum Florya\'da çalışmaktan gurur duyuyor. Hocaların pedagojik yaklaşımı ve teknik çalışma programı harika.',
        englishComment: 'My son is proud to train at Florya. The pedagogical approach of the coaches and technical drills are wonderful.',
        pros: ['Disiplinli Antrenman', 'Kaliteli Çim Zemin'],
        cons: ['Giriş Kartı Sırası'],
        likes: 34,
        tags: ['Altyapı', 'Florya']
      },
      {
        id: 'r-sch1-2',
        userName: 'Murat Kahraman',
        verifiedAttendee: true,
        date: '22 Haziran 2026',
        overallScore: 9.0,
        scores: { antrenor: 9.4, tesis: 8.8, hijyen: 8.5 },
        comment: 'Futbol tekniğinin yanında sporcu ahlakı ve beslenme disiplini de kazandırılıyor. Veliler için tribün ferah.',
        englishComment: 'Teaches athletic morals and nutrition alongside football technique. Viewing stands are spacious for parents.',
        pros: ['Sporcu Disiplini', 'Rahat İzleme Alanı'],
        cons: ['Otopark Ücreti'],
        likes: 21,
        tags: ['Disiplin', 'Veli Tribünü']
      }
    ]
  },
  {
    id: 'school-2',
    title: 'Fenerbahçe Spor Okulları (Dereağzı)',
    slug: 'fb-spor-okullari-dereagzi',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Dereağzı Lefter Küçükandonyadis Tesisleri',
    date: 'Tüm Yıl',
    organizer: 'Fenerbahçe SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=1200&auto=format&fit=crop',
    description: "Fenerbahçe Spor Okulları, basketbol, voleybol ve futbol branşlarında genç yeteneklere eğitim veriyor.",
    overallScore: 8.9,
    ratingBreakdown: { antrenor: 9.2, tesis: 8.8, hijyen: 8.6 },
    reviewCount: 95,
    featured: false,
    isActive: true,
    tags: ['Basketbol', 'Voleybol', 'Futbol'],
    aiSummary: {
      tr: 'Dereağzı Lefter Küçükandonyadis Tesisleri çoklu branş (basketbol, futbol, voleybol) yapısıyla çocukların spor disiplinini erken yaşta kazanmasını sağlar.',
      en: 'Dereağzı Lefter Küçükandonyadis Complex excels in multi-sport youth development (basketball, football, volleyball) with strong discipline.',
      highlightsTr: ['Çoklu Branş Seçenekleri', 'Deneyimli Altyapı Kadrosu', 'Servis Düzeni'],
      highlightsEn: ['Multi-Sport Options', 'Experienced Youth Coaches', 'Organized Shuttles']
    },
    reviews: [
      {
        id: 'r-sch2-1',
        userName: 'Ozan Kaan',
        verifiedAttendee: true,
        date: '04 Temmuz 2026',
        overallScore: 9.0,
        scores: { antrenor: 9.3, tesis: 8.9, hijyen: 8.7 },
        comment: 'Dereağzı salonlarındaki havalandırma ve parke kalitesi mükemmel. Basketbol ve voleybol için harika ortam.',
        englishComment: 'Ventilation and hardwood court quality at Dereağzı halls are great. Perfect environment for basketball and volleyball.',
        pros: ['Kaliteli Parke Zemin', 'İlgili Koçlar'],
        cons: ['Kadıköy Trafiği'],
        likes: 19,
        tags: ['Basketbol', 'Voleybol']
      }
    ]
  },
  {
    id: 'school-3',
    title: 'Beşiktaş Basketbol Okulu (Akatlar)',
    slug: 'bjk-basketbol-okulu-akatlar',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Akatlar Spor Kompleksi',
    date: 'Tüm Yıl',
    organizer: 'Beşiktaş JK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?q=80&w=1200&auto=format&fit=crop',
    description: "Beşiktaş Basketbol Okulu ile çocuklar basketbolun temel becerilerini profesyonel şartlarda öğreniyor.",
    overallScore: 8.7,
    ratingBreakdown: { antrenor: 8.9, tesis: 8.5, hijyen: 8.7 },
    reviewCount: 82,
    featured: false,
    isActive: true,
    tags: ['Basketbol', 'Altyapı'],
    aiSummary: {
      tr: 'Akatlar Spor Kompleksi parke zemini ve antrenör tecrübesiyle çocuklara fundamental basketbol eğitimini yüksek kalitede sunmaktadır.',
      en: 'Akatlar Sports Complex delivers high-quality fundamental basketball drills supported by professional parquet courts and experienced coaches.',
      highlightsTr: ['Akatlar Parke Zemin', 'Fundamental Odaklı', 'Ulaşım Kolaylığı'],
      highlightsEn: ['Pro Parquet Courts', 'Fundamental Drills', 'Easy Access']
    },
    reviews: [
      {
        id: 'r-sch3-1',
        userName: 'Sarp Ünal',
        verifiedAttendee: true,
        date: '12 Mayıs 2026',
        overallScore: 8.8,
        scores: { antrenor: 9.0, tesis: 8.6, hijyen: 8.8 },
        comment: 'Akatlar salonunun havası ve pota kalitesi tam profesyonel seviyede. Antrenörler şut ve top hakimiyeti üzerine titizlikle duruyor.',
        englishComment: 'Akatlar arena atmosphere and hoop quality are professional-grade. Coaches pay diligent attention to shooting and ball handling.',
        pros: ['Profesyonel Potalar', 'Şut Tekniği Eğitimi'],
        cons: ['Hafta Sonu Otoparkı'],
        likes: 15,
        tags: ['Basketbol', 'Akatlar']
      }
    ]
  },
  {
    id: 'school-4',
    title: 'Eczacıbaşı Voleybol Okulu',
    slug: 'eczacibasi-voleybol-okulu',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Ayazağa Spor Salonu',
    date: 'Tüm Yıl',
    organizer: 'Eczacıbaşı Spor Kulübü',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1593786477114-61cbf51bf18b?q=80&w=1200&auto=format&fit=crop',
    description: "Türkiye'nin köklü voleybol kulübü Eczacıbaşı, geleceğin yıldız kız voleybolcularını arıyor.",
    overallScore: 9.5,
    ratingBreakdown: { antrenor: 9.8, tesis: 9.2, hijyen: 9.5 },
    reviewCount: 210,
    featured: true,
    isActive: true,
    tags: ['Voleybol', 'Kız Sporu', 'Profesyonel'],
    aiSummary: {
      tr: 'Ayazağa Spor Salonu\'nda verilen voleybol eğitimi steril ortamı, dünya standartlarındaki esnek tara tara fileleri ve usta antrenörleriyle 10 üzerinden 10 puan almaktadır.',
      en: 'Eczacıbaşı Volleyball School in Ayazağa scores top marks for its sterile facilities, world-class net setups, and master-level youth coaching.',
      highlightsTr: ['Dünya Şampiyonu Altyapı', 'Steril Tesis Hijyeni', 'Bilimsel Sporcu Takibi'],
      highlightsEn: ['World-Class Academy', 'Sterile Hygiene', 'Scientific Athlete Tracking']
    },
    reviews: [
      {
        id: 'r-sch4-1',
        userName: 'Elif Alkan',
        verifiedAttendee: true,
        date: '18 Temmuz 2026',
        overallScore: 9.6,
        scores: { antrenor: 9.9, tesis: 9.4, hijyen: 9.5 },
        comment: 'Kızım için harika bir okul. Eczacıbaşı kültürünü küçük yaşta almak büyük şans. Soyunma odaları ve salon pırıl pırıl.',
        englishComment: 'An absolute dream school for my daughter. Gaining Eczacıbaşı culture early is a true blessing. Cleanliness is 10/10.',
        pros: ['Steril Hijyen', 'Dünya Seviyesinde Koçluk', 'Gelişim Takibi'],
        cons: ['Kayıt Kontenjanı Çabuk Doluyor'],
        likes: 47,
        tags: ['Voleybol', 'Eczacıbaşı']
      }
    ]
  },
  {
    id: 'school-5',
    title: 'Darüşşafaka Basketbol Altyapı',
    slug: 'darussafaka-basketbol-altyapi',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'Darüşşafaka Ayhan Şahenk Spor Salonu',
    date: 'Tüm Yıl',
    organizer: 'Darüşşafaka SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1627627256672-027a4613d028?q=80&w=1200&auto=format&fit=crop',
    description: "Türk basketbolunun köklü altyapısı Darüşşafaka'da elit düzeyde eğitim imkanı.",
    overallScore: 9.0,
    ratingBreakdown: { antrenor: 9.4, tesis: 8.7, hijyen: 8.9 },
    reviewCount: 150,
    featured: false,
    isActive: true,
    tags: ['Basketbol', 'Altyapı'],
    aiSummary: {
      tr: 'Ayhan Şahenk Spor Salonu basketbol altyapısında akademik disiplin ile teknik basketbol becerileri harmanlanmaktadır.',
      en: 'Ayhan Şahenk Arena combines academic discipline with elite youth basketball skill development.',
      highlightsTr: ['Ayhan Şahenk Kompleksi', 'Akademik & Sporcu İklimi', 'Sert Parke Kalitesi'],
      highlightsEn: ['Ayhan Şahenk Complex', 'Academic Athletic Balance', 'Solid Parquet']
    },
    reviews: [
      {
        id: 'r-sch5-1',
        userName: 'Kerem Turgut',
        verifiedAttendee: true,
        date: '02 Ağustos 2026',
        overallScore: 9.1,
        scores: { antrenor: 9.5, tesis: 8.8, hijyen: 9.0 },
        comment: 'Ayhan Şahenk salonunda çalışmak çocuklara profesyonel atmosfer hissettiriyor. Koç kadrosu çok disiplinli.',
        englishComment: 'Training at Ayhan Şahenk arena gives kids a pro feeling. The coaching staff maintains excellent discipline.',
        pros: ['Profesyonel Atmosfer', 'Köklü Altyapı'],
        cons: ['Metro Yürüyüş Mesafesi'],
        likes: 26,
        tags: ['Darüşşafaka', 'Basketbol']
      }
    ]
  },
  {
    id: 'school-6',
    title: 'VakıfBank Voleybol Okulu (Üsküdar)',
    slug: 'vakifbank-voleybol-okulu-uskudar',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'VakıfBank Spor Sarayı',
    date: 'Tüm Yıl',
    organizer: 'VakıfBank SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?q=80&w=1200&auto=format&fit=crop',
    description: "Dünya şampiyonu VakıfBank'ın altyapısında voleybol kariyerine adım atın.",
    overallScore: 9.4,
    ratingBreakdown: { antrenor: 9.7, tesis: 9.5, hijyen: 9.1 },
    reviewCount: 300,
    featured: true,
    isActive: true,
    tags: ['Voleybol', 'Profesyonel', 'Avrupa Yakası'],
    aiSummary: {
      tr: 'VakıfBank Spor Sarayı, fitness salonu, fizyoterapi alanı ve profesyonel voleybol sahalarıyla Türkiye\'deki en lüks ve nitelikli voleybol kompleksi kabul ediliyor.',
      en: 'VakıfBank Sports Palace stands out as Turkey\'s premier volleyball complex featuring pro halls, physical therapy rooms, and top-tier training.',
      highlightsTr: ['VakıfBank Spor Sarayı Lüksü', 'Dünya Çapında Altyapı', 'Steril Soyunma Alanları'],
      highlightsEn: ['VakıfBank Palace Luxury', 'World Championship Academy', 'Sterile Locker Rooms']
    },
    reviews: [
      {
        id: 'r-sch6-1',
        userName: 'Nazlı Çetin',
        verifiedAttendee: true,
        date: '14 Ağustos 2026',
        overallScore: 9.5,
        scores: { antrenor: 9.8, tesis: 9.6, hijyen: 9.2 },
        comment: 'VakıfBank Spor Sarayı muazzam bir tesis. Kızımızın gelişimi için her detay en ince ayrıntısına kadar düşünülmüş.',
        englishComment: 'VakıfBank Sports Palace is a monumental facility. Every detail for our daughter\'s progress has been meticulously considered.',
        pros: ['Rüya Gibi Tesis', 'Süper Voleybol Eğitimi'],
        cons: ['Lokasyon Trafiği'],
        likes: 52,
        tags: ['VakıfBank', 'Voleybol']
      }
    ]
  },
  {
    id: 'school-7',
    title: 'ENKA Tenis Okulu (İstinye)',
    slug: 'enka-tenis-okulu-istinye',
    category: 'Spor Okulları',
    city: 'İstanbul',
    venue: 'ENKA Sadi Gülçelik Spor Sitesi',
    date: 'Tüm Yıl',
    organizer: 'ENKA Spor Kulübü',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1200&auto=format&fit=crop',
    description: "Dünya standartlarında kortlarda, milli antrenörler eşliğinde profesyonel tenis eğitimi.",
    overallScore: 9.3,
    ratingBreakdown: { antrenor: 9.1, tesis: 9.8, hijyen: 9.2 },
    reviewCount: 115,
    featured: false,
    isActive: true,
    tags: ['Tenis', 'Raket Sporları', 'Bireysel Sporlar'],
    aiSummary: {
      tr: 'İstinye ENKA Sadi Gülçelik Spor Sitesi açık ve kapalı kort kalitesi, milli tenis antrenörleri ve doğayla iç içe atmosferiyle 1 numaradır.',
      en: 'ENKA Sadi Gülçelik Sports Complex in İstinye reigns supreme with indoor/outdoor clay and hard courts led by national team coaches.',
      highlightsTr: ['Açık & Kapalı Kort Çeşitliliği', 'Milli Tenis Eğitmenleri', 'Yeşil Doğa İçinde'],
      highlightsEn: ['Indoor & Outdoor Court Options', 'National Tennis Instructors', 'Lush Green Campus']
    },
    reviews: [
      {
        id: 'r-sch7-1',
        userName: 'Emre Yıldız',
        verifiedAttendee: true,
        date: '20 Ağustos 2026',
        overallScore: 9.4,
        scores: { antrenor: 9.2, tesis: 9.9, hijyen: 9.3 },
        comment: 'ENKA tesisleri kort bakımı ve ışıklandırma açısından Türkiye\'nin en iyisi. Çocuklar kortta harika teknik kazanıyor.',
        englishComment: 'ENKA court maintenance and lighting are second to none in Turkey. Kids gain solid technical strokes on court.',
        pros: ['Harika Kort Zeminleri', 'Milli Antrenörler'],
        cons: ['Üyelik Fiyatı Yüksek'],
        likes: 28,
        tags: ['Tenis', 'ENKA']
      }
    ]
  },
  {
    id: 'school-8',
    title: 'TED Ankara Kolejliler Basketbol Okulu',
    slug: 'ted-ankara-kolejliler-basketbol',
    category: 'Spor Okulları',
    city: 'Ankara',
    venue: 'TED Ankara Koleji Spor Salonu',
    date: 'Tüm Yıl',
    organizer: 'TED Ankara Kolejliler',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1505666287802-931dc83948e9?q=80&w=1200&auto=format&fit=crop',
    description: "Ankara'nın en saygın basketbol okullarından birinde spora başlama şansı.",
    overallScore: 8.8,
    ratingBreakdown: { antrenor: 9.0, tesis: 8.5, hijyen: 8.8 },
    reviewCount: 140,
    featured: true,
    isActive: true,
    tags: ['Basketbol', 'Ankara', 'Okul Sporları'],
    aiSummary: {
      tr: 'TED Ankara Koleji yerleşkesindeki basketbol okulu köklü Ankara geleneği ve disiplinli parke antrenmanlarıyla takdir kazanmaktadır.',
      en: 'TED Ankara College basketball academy blends Ankara\'s classic basketball tradition with disciplined indoor court training.',
      highlightsTr: ['Köklü Ankara Geleneği', 'Disiplinli Koçlar', 'Temiz Kampüs'],
      highlightsEn: ['Storied Ankara Tradition', 'Disciplined Coaches', 'Pristine Campus']
    },
    reviews: [
      {
        id: 'r-sch8-1',
        userName: 'Burak Arslan',
        verifiedAttendee: true,
        date: '05 Eylül 2026',
        overallScore: 8.9,
        scores: { antrenor: 9.1, tesis: 8.6, hijyen: 9.0 },
        comment: 'Ankara\'da basketbol denince akla gelen ilk adreslerden biri. Eğitmen ilgisi ve salon hijyeni çok iyi.',
        englishComment: 'One of the first academies that comes to mind for basketball in Ankara. Coach care and hall cleanliness are top notch.',
        pros: ['Köklü Disiplin', 'Geniş Otopark'],
        cons: ['Kışın Salon Isınması Bazen Yavaş'],
        likes: 17,
        tags: ['Ankara', 'TED']
      }
    ]
  },
  {
    id: 'school-9',
    title: 'Karşıyaka Yelken ve Su Sporları Okulu',
    slug: 'karsiyaka-yelken-ve-su-sporlari',
    category: 'Spor Okulları',
    city: 'İzmir',
    venue: 'Karşıyaka Yelken Kulübü',
    date: 'Yaz Dönemi',
    organizer: 'Karşıyaka Spor Kulübü',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1533140938495-9ff27e1b9b94?q=80&w=1200&auto=format&fit=crop',
    description: "Denizi ve rüzgarı sevenler için optimist ve yelken eğitimleri.",
    overallScore: 9.2,
    ratingBreakdown: { antrenor: 9.3, tesis: 8.8, hijyen: 9.5 },
    reviewCount: 75,
    featured: false,
    isActive: true,
    tags: ['Yelken', 'Su Sporları', 'İzmir'],
    aiSummary: {
      tr: 'İzmir Karşıyaka yelken kulübü çocuklara deniz sevgisini ve Optimist yelken tekniklerini güvenli bot takibiyle aşılamaktadır.',
      en: 'Karşıyaka Sailing Academy instills a love for the sea and Optimist sailing skills in children backed by strict rescue boat supervision.',
      highlightsTr: ['Optimist ve Laser Eğitimi', 'Deniz Güvenlik Botları', 'Karşıyaka Sahili'],
      highlightsEn: ['Optimist & Laser Drills', 'Sea Safety Escort Boats', 'Karşıyaka Coastline']
    },
    reviews: [
      {
        id: 'r-sch9-1',
        userName: 'Gözde Şahin',
        verifiedAttendee: true,
        date: '12 Temmuz 2026',
        overallScore: 9.3,
        scores: { antrenor: 9.5, tesis: 8.9, hijyen: 9.5 },
        comment: 'Yaz okulunda çocukların deniz güvenliği 1. öncelik. Bot kaptanları ve yelken koçları süper.',
        englishComment: 'Sea safety is priority #1 at the summer academy. Rescue boat captains and sailing coaches are stellar.',
        pros: ['Yüksek Güvenlik', 'Deniz Sevgisi'],
        cons: ['Güneş Koruma İhtiyacı'],
        likes: 22,
        tags: ['Yelken', 'Karşıyaka']
      }
    ]
  },
  {
    id: 'school-10',
    title: 'Göztepe Cimnastik Okulu',
    slug: 'goztepe-cimnastik-okulu',
    category: 'Spor Okulları',
    city: 'İzmir',
    venue: 'Gürsel Aksel Tesisleri',
    date: 'Tüm Yıl',
    organizer: 'Göztepe SK',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1579213166547-5a1e74f44fa6?q=80&w=1200&auto=format&fit=crop',
    description: "Çocukların fiziksel gelişimine katkıda bulunan temel cimnastik eğitimleri.",
    overallScore: 8.6,
    ratingBreakdown: { antrenor: 8.9, tesis: 8.2, hijyen: 8.6 },
    reviewCount: 90,
    featured: false,
    isActive: true,
    tags: ['Cimnastik', 'Temel Spor', 'Çocuk Gelişimi'],
    aiSummary: {
      tr: 'Gürsel Aksel Tesisleri\'nde verilen temel cimnastik eğitimi esneklik, denge ve koordinasyonu geliştirmek için harika minder ve mat donanımına sahiptir.',
      en: 'Gürsel Aksel Gym academy provides an ideal setup of safety mats and bars for building youth flexibility, balance, and coordination.',
      highlightsTr: ['Darbe Emici Minderler', 'Denge ve Esneklik Odaklı', 'Velilere Özel Alan'],
      highlightsEn: ['Shock-Absorbing Mats', 'Balance & Mobility Focus', 'Dedicated Parent Seating']
    },
    reviews: [
      {
        id: 'r-sch10-1',
        userName: 'Aslı Varol',
        verifiedAttendee: true,
        date: '28 Temmuz 2026',
        overallScore: 8.7,
        scores: { antrenor: 9.0, tesis: 8.3, hijyen: 8.8 },
        comment: '4 yaşındaki kızım esneklik ve denge hareketlerini severek yapıyor. Minderler ve koruyucu matlar çok güvenli.',
        englishComment: 'My 4-year-old daughter loves the flexibility and balance drills. Safety mats and protective gear are very reassuring.',
        pros: ['Darbe Emici Matlar', 'Şefkatli Eğitmenler'],
        cons: ['Giriş Park Yeri'],
        likes: 14,
        tags: ['Cimnastik', 'Göztepe']
      }
    ]
  },
  {
    id: 'event-rep-1',
    title: 'Boğaziçi Kıtalararası Yüzme Yarışı 2026',
    slug: 'bogazici-yuzme-yarisi-2026',
    category: 'Spor Etkinlikleri',
    city: 'İstanbul',
    venue: 'İstanbul Boğazı (Kanlıca-Kuruçeşme)',
    date: '23 Ağustos 2026',
    organizer: 'Türkiye Milli Olimpiyat Komitesi',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1519315901367-f34f828a2a7a?q=80&w=1200&auto=format&fit=crop',
    description: "Dünyanın en iyi açık su yüzme organizasyonlarından biri. İki kıta arası yüzme heyecanı.",
    overallScore: 9.8,
    ratingBreakdown: { organizasyonAkis: 9.7, parkurGuvenlik: 9.9, atmosferSeyir: 10.0 },
    reviewCount: 520,
    featured: true,
    isActive: true,
    tags: ['Yüzme', 'Açık Su', 'Uluslararası'],
    aiSummary: {
      tr: 'Kanlıca\'dan Kuruçeşme\'ye İstanbul Boğazı\'nı gemi trafiğine kapatarak yüzme deneyimi sunan organizasyon, bot güvenliği ve çip zamanlamasıyla dünyada eşsizdir.',
      en: 'Swimming across the Bosphorus from Kanlıca to Kuruçeşme with closed maritime traffic offers a world-renowned open water race backed by top-tier rescue boats and chip timing.',
      highlightsTr: ['Boğaz Trafiğe Kapalı', 'Üst Düzey Bot Güvenliği', 'Eşsiz Kıtalararası Parkur'],
      highlightsEn: ['Closed Bosphorus Traffic', 'Elite Safety Boat Fleet', 'Iconic Cross-Continental Route']
    },
    reviews: [
      {
        id: 'r-ev1-1',
        userName: 'Metehan Şen',
        verifiedAttendee: true,
        date: '24 Ağustos 2026',
        overallScore: 9.9,
        scores: { organizasyonAkis: 9.8, parkurGuvenlik: 10.0, atmosferSeyir: 10.0 },
        comment: 'Asya\'dan Avrupa\'ya kulvar açmak hayatımın en gururlu anıydı. TMOK organizasyonu ve deniz bot takibi eksiksizdi.',
        englishComment: 'Swimming from Asia to Europe was the proudest moment of my life. Turkish NOC organization and boat escorts were flawless.',
        pros: ['Kusursuz Organizasyon', 'Eşsiz Manzara', 'Güvenlik Botları'],
        cons: ['Akıntı Okumak Zor'],
        likes: 112,
        tags: ['Boğaziçi', 'Yüzme']
      },
      {
        id: 'r-ev1-2',
        userName: 'Elena Rostova',
        verifiedAttendee: true,
        date: '25 Ağustos 2026',
        overallScore: 9.7,
        scores: { organizasyonAkis: 9.6, parkurGuvenlik: 9.8, atmosferSeyir: 9.8 },
        comment: 'Yurt dışından bu yarış için gelmek her ana değdi. Kuruçeşme Parkı\'ndaki organizasyon mükemmel bir şekilde işledi.',
        englishComment: 'Traveling from abroad for this race was worth every moment. The organization in Kuruçeşme Park was perfectly streamlined.',
        pros: ['Uluslararası Standart', 'Harika Atmosfer'],
        cons: ['Kayıt kontenjanları hızlı doluyor'],
        likes: 67,
        tags: ['Bosphorus', 'OpenWater']
      }
    ]
  },
  {
    id: 'event-rep-2',
    title: 'Kapadokya Ultra Trail 2026',
    slug: 'kapadokya-ultra-trail-2026',
    category: 'Spor Etkinlikleri',
    city: 'Nevşehir',
    venue: 'Ürgüp Şehir Merkezi',
    date: '17 Ekim 2026',
    organizer: 'Argeus Events',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1605335626244-933e496a7ce9?q=80&w=1200&auto=format&fit=crop',
    description: "Peribacalarının arasında gerçekleşen, dünyanın dört bir yanından sporcuları ağırlayan ultra maraton.",
    overallScore: 9.7,
    ratingBreakdown: { organizasyonAkis: 9.6, parkurGuvenlik: 9.5, kitIkram: 9.8 },
    reviewCount: 380,
    featured: true,
    isActive: true,
    tags: ['Koşu', 'Ultra Maraton', 'Doğa Sporları'],
    aiSummary: {
      tr: 'Nevşehir Ürgüp vadilerinde ve peribacaları patikalarında düzenlenen yarıştaki Check-Point (CP) ikramları, parkur bayraklaması ve gönüllü enerjisi mükemmeldir.',
      en: 'Organized through the fairy chimneys of Cappadocia, this ultra marathon receives acclaim for rich CP stations, flag markings, and volunteer energy.',
      highlightsTr: ['Peribacaları Parkuru', 'Zengin CP İkramları', 'Harika Gönüllü İlgisi'],
      highlightsEn: ['Fairy Chimney Trail', 'Abundant CP Refreshments', 'Superb Volunteer Support']
    },
    reviews: [
      {
        id: 'r-ev2-1',
        userName: 'Tolga Pekcan',
        verifiedAttendee: true,
        date: '18 Ekim 2026',
        overallScore: 9.8,
        scores: { organizasyonAkis: 9.7, parkurGuvenlik: 9.6, kitIkram: 9.9 },
        comment: 'CP istasyonlarındaki sıcak çorba, meyve ve gönüllü desteği 60. kilometrede hayat kurtardı. Gece etabındaki refleks şeritler çok netti.',
        englishComment: 'Hot soup, fruits, and volunteer cheers at CP stations were lifesavers at km 60. Reflective markers for night stages were razor clear.',
        pros: ['Kusursuz İşaretleme', 'Zengin CP Masaları', 'Büyüleyici Doğa'],
        cons: ['Zorlu İrtifa'],
        likes: 83,
        tags: ['UltraMaraton', 'Kapadokya']
      }
    ]
  },
  {
    id: 'event-rep-3',
    title: 'İstanbul Yarı Maratonu 2026',
    slug: 'istanbul-yari-maratonu-2026',
    category: 'Spor Etkinlikleri',
    city: 'İstanbul',
    venue: 'Tarihi Yarımada',
    date: '5 Nisan 2026',
    organizer: 'Spor İstanbul',
    organizerVerified: true,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=1200&auto=format&fit=crop',
    description: "Dünyanın en hızlı yarı maraton parkurlarından birinde kıyasıya mücadele ve tarihi manzara.",
    overallScore: 9.2,
    ratingBreakdown: { organizasyonAkis: 9.0, parkurGuvenlik: 9.4, atmosferSeyir: 9.5 },
    reviewCount: 415,
    featured: false,
    isActive: true,
    tags: ['Koşu', 'Yarı Maraton', 'Atletizm'],
    aiSummary: {
      tr: 'Haliç ve Tarihi Yarımada sahilindeki tamamen düz parkur, kişisel en iyi derece (PB) koşmak isteyen atletler için Türkiye\'nin en hızlı maratonudur.',
      en: 'Featuring a completely flat course along the Golden Horn and Historical Peninsula, this is Turkey\'s fastest half marathon for setting a Personal Best (PB).',
      highlightsTr: ['Düz ve Hızlı Parkur', 'Tarihi Yarımada Manzarası', 'Bol Su ve İzo İçecek Noktası'],
      highlightsEn: ['Flat & Fast PB Course', 'Historical Peninsula Views', 'Frequent Water & Isotonic Hubs']
    },
    reviews: [
      {
        id: 'r-ev3-1',
        userName: 'Ceren Akman',
        verifiedAttendee: true,
        date: '06 Nisan 2026',
        overallScore: 9.3,
        scores: { organizasyonAkis: 9.1, parkurGuvenlik: 9.5, atmosferSeyir: 9.4 },
        comment: 'Haliç kıyısındaki dümdüz parkur sayesinde kişisel rekorumu (PB) kırdım! Su istasyonları ve finish madalyası harikaydı.',
        englishComment: 'Broke my Personal Best (PB) thanks to the perfectly flat course along the Golden Horn! Hydration hubs and finish medal were amazing.',
        pros: ['Hızlı PB Parkuru', 'Harika Finish Madalyası'],
        cons: ['Emanet Çanta Kuyruğu'],
        likes: 49,
        tags: ['YarıMaraton', 'Koşu']
      }
    ]
  }
];

import { CorporateApplication } from '../types';

export const INITIAL_CORPORATE_APPS: CorporateApplication[] = [
  {
    id: 'SP-KUR-987654',
    refCode: 'SP-KUR-987654',
    facilityName: 'Şampiyon Halı Saha',
    category: 'Spor Tesisleri',
    city: 'İstanbul',
    district: 'Kadıköy',
    address: 'Fenerbahçe Mah. Stadyum Sok. No: 5',
    contactName: 'Ahmet Yılmaz',
    contactTitle: 'Tesis Müdürü',
    contactEmail: 'iletisim@sampiyonhalisaha.com',
    contactPhone: '0555 123 45 67',
    website: 'https://sampiyonhalisaha.com',
    capacity: '14 Kişi / Maç',
    amenities: ['Otopark', 'Duş & Soyunma Odası', 'Kafeterya', 'Aydınlatma', 'Kiralık Ekipman'],
    imageUrl: 'https://images.unsplash.com/photo-157952363873-27f3bade9f55?q=80&w=800&auto=format&fit=crop',
    description: 'Kadıköy\'ün en iyi zeminine sahip halı sahası. Gece maçları için profesyonel aydınlatma sistemimiz mevcultur.',
    taxOffice: 'Kadıköy',
    taxNumber: '1234567890',
    licenseNumber: 'GSİM-2023-001',
    workingHours: '08:00 - 02:00',
    membershipFeeRange: 'Saatlik 1200 ₺',
    status: 'pending',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'SP-KUR-123456',
    refCode: 'SP-KUR-123456',
    facilityName: 'MacFit Ataşehir',
    category: 'Spor Tesisleri',
    city: 'İstanbul',
    district: 'Ataşehir',
    address: 'Barbaros Mah. Mor Sümbül Sok.',
    contactName: 'Mehmet Demir',
    contactTitle: 'Kulüp Yöneticisi',
    contactEmail: 'atasehir@macfit.com',
    contactPhone: '0216 123 45 67',
    website: 'https://macfit.com',
    capacity: '500+ Kişi',
    amenities: ['Otopark', 'Duş & Soyunma Odası', 'Fitness Alanı', 'Grup Dersleri', 'Kişisel Antrenör', 'Kafeterya'],
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
    description: "En son teknoloji ekipmanlarla donatılmış geniş fitness alanı ve zengin grup dersleri seçenekleri.",
    taxOffice: 'Ataşehir',
    taxNumber: '0987654321',
    licenseNumber: 'GSİM-2022-045',
    workingHours: '06:00 - 23:00',
    membershipFeeRange: 'Aylık 1500 ₺ - 2500 ₺',
    status: 'approved',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    publishedFacilityId: '2',
  },
];
